spring:
  application:
    name: order-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 4000

scalar:
  enabled: true
  url: /openapi.yaml
  path: /docs
