spring:
  application:
    name: order-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: order-service-group
      auto-offset-reset: earliest

server:
  port: 4001

scalar:
  enabled: true
  url: /openapi-order-service.yaml
  path: /api-docs-order-service
