spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: http://order-service:4000
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=1

            - id: inventory-service-route
              uri: http://inventory-service:4001
              predicates:
                - Path=/api/inventory/**
              filters:
                - StripPrefix=1

server:
  port: 4004
