spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: http://order-service:4001
              predicates:
                - Path=/orders/**
              filters:
                - JwtValidation

            - id: order-service-docs-route
              uri: http://order-service:4001
              predicates:
                - Path=/api-docs-order-service/**

            - id: order-service-openapi-route
              uri: http://order-service:4001
              predicates:
                - Path=/openapi-order-service.yaml

            - id: payment-service-route
              uri: http://payment-service:4002
              predicates:
                - Path=/payments/**

            - id: inventory-service-route
              uri: http://inventory-service:4003
              predicates:
                - Path=/inventory/**

            - id: auth-service-route
              uri: http://auth-service:4004
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

server:
  port: 4000
